version: 0.2

phases:
  install:
    runtime-versions:
      # update to latest supported node version
      nodejs: 22
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'
