version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - UPLOAD_BUCKET=imagasaur-uploads-local
      - PROCESSED_BUCKET=imagasaur-processed-local
    volumes:
      - ./backend:/app
    networks:
      - imagasaur-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - imagasaur-network

networks:
  imagasaur-network:
    driver: bridge
