version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - UPLOAD_BUCKET=imagasaur-uploads-dev-sowfp0ck
      - PROCESSED_BUCKET=imagasaur-processed-dev-sowfp0ck
      - AWS_PROFILE=stegasaur
    volumes:
      - ./backend:/app
      - ~/.aws:/home/app/.aws:ro
    networks:
      - imagasaur-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - imagasaur-network
    stdin_open: true
    tty: true

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./lambda:/lambda
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack
    networks:
      - imagasaur-network

volumes:
  localstack-data:

networks:
  imagasaur-network:
    driver: bridge
