version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - UPLOAD_BUCKET=imagasaur-uploads-dev-sowfp0ck
      - PROCESSED_BUCKET=imagasaur-processed-dev-sowfp0ck
      - AWS_PROFILE=stegasaur
    volumes:
      - ./backend:/app
      - ~/.aws:/home/app/.aws:ro
    networks:
      - imagasaur-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - imagasaur-network
    stdin_open: true
    tty: true

networks:
  imagasaur-network:
    driver: bridge
